# Workflow navn og triggers
name: Build and Deploy JAR app to Azure Web App - TheRealWishList

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Check out koden fra repository
      - uses: actions/checkout@v4

      # Opsæt Java JDK 17 med caching af Maven-afhængigheder for hurtigere builds
      - name: Set up Java version
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      # Byg projektet med Maven
      - name: Build with Maven
        env:
          DB_URL: ${{ secrets.DB_URL }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        run: mvn clean package --file pom.xml

      # Upload artifact (det færdige JAR) til brug i deploy-trinnet
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: java-app
          path: '${{ github.workspace }}/target/*.jar'

      # Download artifact og deploy til Azure Web App
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: java-app

      # Login til Azure
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      # Deploy til Azure Web App
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'TheRealWishList'
          package: '*.jar'